CREATE ROLE clienthub_migration
    LOGIN PASSWORD 'migration_test_password'
    NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE clienthub_runtime
    LOGIN PASSWORD 'runtime_test_password'
    NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE clienthub_app
    NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;

ALTER DATABASE managed_role_test OWNER TO clienthub_migration;
ALTER SCHEMA public OWNER TO clienthub_migration;
GRANT CONNECT ON DATABASE managed_role_test TO clienthub_runtime;
