CREATE ROLE clienthub_runtime LOGIN PASSWORD 'runtime_test_password' NOSUPERUSER NOBYPASSRLS;

GRANT CONNECT ON DATABASE test TO clienthub_runtime;
GRANT USAGE ON SCHEMA public TO clienthub_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO clienthub_runtime;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO clienthub_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO clienthub_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO clienthub_runtime;
